api_platform:
  http_cache:
    invalidation:
      enabled: true
    public: true
  defaults:
    cache_headers:
      max_age: 0
      shared_max_age: 3600
  swagger:
    swagger_ui_extra_configuration:
      defaultModelsExpandDepth: -1